FROM python:3.11

RUN apt-get update

WORKDIR /opt/app

COPY tests/pyproject.toml ./
COPY tests/poetry.lock ./

RUN apt-get update \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-dev

COPY tests tests
COPY lib lib

CMD ["pytest"]
