version: '3'

services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
    env_file:
      - .env
    ports:
      - "${TEST_DB_PORT}:${TEST_DB_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    restart: always
    networks:
      - tests_network

  api:
    build:
      context: .
    container_name: api
    image: fastapi_app
    restart: always
    entrypoint: [ "/opt/app/entrypoint.sh" ]
    env_file:
      - .env
    expose:
      - "${API_PORT}"
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - postgres

  tests:
    build:
      context: .
      dockerfile: "Dockerfile.tests"
    env_file:
      - .env
    depends_on:
      - postgres


volumes:
  postgres_data:

networks:
  tests_network:
    driver: bridge
