version: "3"

services:
  bot:
    image: "${BOT_IMAGE_NAME:-tg_bot-image}"
    container_name: "${BOT_CONTAINER_NAME:-tg_bot-container}"
    build:
      context: .
    restart: always
    env_file:
      - .env
    networks:
      - tg_bot_network

networks:
  tg_bot_network:
    driver: bridge
