version: "3"

services:
  api:
    build:
      context: .
    ports:
      - "${API_PORT}:${API_PORT}"
    expose:
      - ${API_PORT}
    env_file:
      - .env

  nginx:
    image: nginx:1.25.1
    restart: always
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/templates:/etc/nginx/templates
    ports:
      - "${NGINX_PORT}:${NGINX_PORT}"
    depends_on:
      - api

networks:
  default:
    driver: bridge
