import enum


class BaseLanguageCodesEnum(enum.Enum):
    RUSSIAN = "ru"
    ENGLISH = "en"
    KAZAKH = "kk"
    GERMAN = "de"
    HEBREW = "he"
    UZBEK = "uz"
    JAPANESE = "ja"
    CHINESE = "zh"
    HINDI = "hi"
    FRENCH = "fr"
    KOREAN = "ko"
    PORTUGUESE = "pt"
    ITALIAN = "it"
    SPANISH = "es"
    INDONESIAN = "id"
    DUTCH = "nl"
    TURKISH = "tr"
    FILIPINO = "fil"
    POLISH = "pl"
    SWEDISH = "sv"
    BULGARIAN = "bg"
    ROMANIAN = "ro"
    ARABIC = "ar"
    CZECH = "cs"
    GREEK = "el"
    FINNISH = "fi"
    CROATIAN = "hr"
    MALAY = "ms"
    SLOVAK = "sk"
    DANISH = "da"
    TAMIL = "ta"
    UKRAINIAN = "uk"


class ElevenLabsLanguageCodesEnum(enum.Enum):
    RUSSIAN = "ru"
    ENGLISH = "en"
    KAZAKH = "kk"
    GERMAN = "de"
    HEBREW = "he"
    UZBEK = "uz"
    JAPANESE = "ja"
    CHINESE = "zh"
    HINDI = "hi"
    FRENCH = "fr"
    KOREAN = "ko"
    PORTUGUESE = "pt"
    ITALIAN = "it"
    SPANISH = "es"
    INDONESIAN = "id"
    DUTCH = "nl"
    TURKISH = "tr"
    FILIPINO = "fil"
    POLISH = "pl"
    SWEDISH = "sv"
    BULGARIAN = "bg"
    ROMANIAN = "ro"
    ARABIC = "ar"
    CZECH = "cs"
    GREEK = "el"
    FINNISH = "fi"
    CROATIAN = "hr"
    MALAY = "ms"
    SLOVAK = "sk"
    DANISH = "da"
    TAMIL = "ta"
    UKRAINIAN = "uk"


class YandexLanguageCodesEnum(enum.Enum):
    RUSSIAN = "ru-RU"
    ENGLISH = "en-US"
    KAZAKH = "kk-KK"
    GERMAN = "de-DE"
    HEBREW = "he-IL"
    UZBEK = "uz-UZ"


LANGUAGE_CODES_ENUM_TYPE = BaseLanguageCodesEnum | ElevenLabsLanguageCodesEnum | YandexLanguageCodesEnum
